---
version: '3'
services:
  registry:
    image: registry:latest
    ports:
      - '5000:5000'
    volumes:
      - $PWD/data/:/var/lib/registry 
      - $PWD/auth:/auth 
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd

