---
version: '3'
services:
  registry:
    image: registry:latest
    ports:
      - '443:443'
    volumes:
      - $PWD/data/:/var/lib/registry 
      - $PWD/auth:/auth 
      - $PWD/certs:/certs

    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key

